server:
  port: 8081
  mode: debug

mysql:
  host: 127.0.0.1
  port: 3306
  username: gohub_app
  password: ""
  database: gohub
  charset: utf8mb4

redis:
  addr: "127.0.0.1:6381"
  password: ""
  db: 0

jwt:
  secret: ""
  expire_hours: 24